name: My Workflow

on:
  repository_dispatch:
    types: [manual-trigger]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is allowed to trigger workflow
        run: |
          if [[ ! "${{ secrets.ALLOWED_USERS }}" =~ (^|,)${{ github.actor }}(,|$) ]]; then
            echo "Only specific users are allowed to trigger this workflow."
            exit 1
          fi
      - name: Run workflow
        run: echo "Hello, world!"
