name: Pre-merge test

on:
  pull_request:
    branches: ["main"]
    paths: 
      - "components/test/**"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run workflow
        run: |
          if [[ $${{ github.event_path }} == *"components/test"* ]]; then
          cd components/test
          ls
          echo "Testing GH Actions!"
