name: Pre-merge test

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'components/test/**'

  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run tests
        if: ${{ github.event_path == 'components/test' }}
        run: |
          cd contents/test
          ls
          echo "testing pull_request workflow"

  

