name: Pre-merge test

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:
              - 'components/test/**'
            path2:
              - 'components/test2/**'
      
      - name: Run tests
        if: steps.filter.outputs.path1 == 'true'
        run: |
          cd components/test
          ls
          echo "testing pull_request workflow"

  

