name: Pre-merge test

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:
              - 'components/test/**'
            path2:
              - 'components/test2/**'
      
      - name: Run path 1
        if: steps.filter.outputs.path1 == 'true'
        run: |
          cd components/test
          ls
          echo "testing path 1"
          
      - name: Run path 2
        if: steps.filter.outputs.path2 == 'true'
        run: |
          cd components/test2
          ls
          echo "testing path 2"
  

